version: '3.8'

services:
  server:
      environment:
        - CHOKIDAR_USEPOLLING=true
      build:
        dockerfile: Dockerfile
        context: ./server
      volumes:
        - /app/node_modules
        - ./server:/app
      ports:
        - '8080:4000'
  web:
      environment:
        - CHOKIDAR_USEPOLLING=true
      build:
        dockerfile: Dockerfile
        context: ./web
      volumes:
        - /app/node_modules
        - ./web:/app
      ports:
        - '8081:3000'