version: "3"

services:
  server:
    build:
      context: ./server
    environment:
      - SERVER_PORT=8080
    ports:
      - "8080:8080"

  client_mobile:
    build:
      context: ./mobile
      dockerfile: Dockerfile
    depends_on:
      - server
    volumes:
      - apk:/usr/src/app/android/app/build/outputs/apk/:rw
  
  client_web:
    build:
      context: ./web
    environment:
      - WEB_CLIENT_PORT=8081
    depends_on:
      - client_mobile
    volumes:
      - apk:/var/www/:ro
    ports:
      - "8081:3000"

volumes:
  apk: