version: "3"

services:
  client_mobile:
    build:
      context: ./mobile/
      dockerfile: Dockerfile
    command: bash -c "cp ./android/app/build/outputs/apk/release/app-release.apk /usr/apkBuild/client.apk"
    volumes:
      - ./mobile/:/usr/app
      - apk-volume:/usr/apkBuild

  server:
    build:
      context: ./server
    environment:
      - SERVER_PORT=8080
      - TOKEN=MTA2MzA1NDI3Mzk0NjA1ODgzMw.GIQFni.gvk0iQnZ49jGAcOXwBz22h6kKpiv7Npczly8o4
    ports:
      - "8080:8080"
    volumes:
      - apk-volume:/usr/apkBuild

  client_web:
    build:
      context: ./web
    environment:
      - WEB_CLIENT_PORT=8081
    depends_on:
      - client_mobile
      - server
    ports:
      - "8081:3000"
    volumes:
      - apk-volume:/usr/apkBuild

volumes:
  apk-volume: