version: "3"

services:
  server:
    build:
      context: ./server
    environment:
      - SERVER_PORT=8080
    ports:
      - "8080:8080"
  
  client_web:
    build:
      context: ./web
    depends_on:
      - server
    volumes:
      - commun:/apk
    ports:
      - "8081:3000"

volumes:
  commun: