version: '3.8'

services:
  client:
      stdin_open: true
      environment:
        - CHOKIDAR_USEPOLLING=true
      build:
        dockerfile: Dockerfile
        context: ./web
      volumes:
        - /app/node_modules
        - ./web:/app
      ports:
        - '8081:3000'