version: '3.7'

services:

  client_web:
    container_name: client_web
    build:
      context: ./clientWeb
      dockerfile: Dockerfile
    volumes:
      - ./clientWeb:/app'
      - /app/node_modules
    ports:
      - '8081:3000'
    environment:
      - CHOKIDAR_USEPOLLING=true