version: '3.7'

services:

  server:
    container_name: server
    build:
      context: ./server
      dockerfile: Dockerfile
    depends_on:
      -
    volumes:
      -
    ports:
      - 8080:8080
    environment:
      -

  client_mobile:
    container_name: client_mobile
    build:
      context: ./clientMobile
      dockerfile: Dockerfile
    depends_on:
      - server
    volumes:
      -
    ports:
      -
    environment:
      -

  client_web:
    container_name: client_web
    build:
      context: ./clientWeb
      dockerfile: Dockerfile
    depends_on:
      - client_mobile
    volumes:
      - ./clientWeb:/app'
      - /app/node_modules
    ports:
      - '8081:3000'
    environment:
      - CHOKIDAR_USEPOLLING=true  